stages:
  - build
  - lint
  - test

.backend-rules:
  rules:
    #Запуск пайплайна для MR.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - backend/**/*

    #Запуск пайплайна при слиянии в dev или master. Позволяет запустить пайплайн на актуальной кодовой базе
    - if: ($CI_COMMIT_BRANCH == 'dev' || $CI_COMMIT_BRANCH == 'master')
      changes:
        - backend/**/*

.frontend-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        frontend/**/*

    - if: ($CI_COMMIT_BRANCH == 'dev' || $CI_COMMIT_BRANCH == 'master')
      changes:
        frontend/**/*

.frontend-base:
  image: node:26
  cache:
    key: frontend-npm-cache
    paths:
      - frontend/.npm/
  before_script:
    - cd frontend/
    - npm ci

.backend-base:
  image: maven:3.9.14-eclipse-temurin-25
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/backend/.m2/repository"
  cache:
    key: backend-maven-cache
    paths:
      - backend/.m2/repository
  before_script:
    - cd backend

build-backend:
  stage: build
  extends:
    - .backend-base
    - .backend-rules
  script:
    - echo 'Сборка приложения'
    - mvn package -DskipTests
  artifacts:
    paths:
      - backend/target/
    expire_in: 1 hour

lint-backend:
  stage: lint
  extends:
    - .backend-base
    - .backend-rules
  needs:
    - build-backend
  script:
    - echo 'Запуск линтеров'
    - mvn spotless:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check

test-backend:
  stage: test
  extends:
    - .backend-rules
    - .backend-base
  needs:
    - lint-backend
  script:
    - echo 'Запуск тестов'
    - mvn verify

build-frontend:
  stage: build
  extends:
    - .frontend-base
    - .frontend-rules
  script:
    - echo 'Запуск сборки'
    - npm run build
  artifacts:
    paths:
      - frontend/build/
    expire_in: 1 hour

lint-frontend:
  stage: lint
  needs:
    - build-frontend
  extends:
    - .frontend-base
    - .frontend-rules
  script:
    - echo 'Запуск линтеров'
    - npm run lint

test-frontend:
  stage: test
  needs:
    - lint-frontend
  extends:
    - .frontend-base
    - .frontend-rules
  script:
    - echo 'Запуск тестов'
    - npm run test